### ISSUE TITLE
Different name

### ISSUE THREAD

**Issue by paldepind** [danr/ts-quickcheck#7]
I was sharing ts-quickcheck with a friend and he pointed out that the name might give people the impression that the library is TypeScript only. But even though ts-quickcheck is implemented in TypeScript it can equally well be used in JavaScript (and potentially also with Flow).

What about changing the name to something without "ts" in it? I don't have any original ideas but at least `proptest` is free on npm.

**Comment by limemloh** [comment]
I have some suggestions: 
* `Protest` - Like in property-testing and because it is also a pro way of testing 😎 
* `Prophet`
* `Propaganda`
* `Propane`

All names are already taken on npm, but most of them look inactive and you might have luck [adopting](https://www.npmjs.com/policies/disputes) one of the names:

**Comment by danr** [comment]
I certainly like `proptest` but I also would like it to preserve the `quickcheck` name part in homage to the original haskell library. I've pinged the author of the empty `qc` package if they would be interested in letting me adopt that name.

**Comment by danr** [comment]
Renamed to `proptest` and released a preliminary version to npm.
